openapi: 3.0.0
info:
  title: Cloud Game Store Service - Invoice Service
  description: Invoice service for Cloud Game Store Implementation.
  version: 0.0.1
servers:
  - url: http://localhost:7002
    description: Invoice Service

paths:
  /invoice:
    post:
      summary: add invoice
      description: add a new invoice by submmitting all fields except invoiceId.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '201':
          description: Returns added invoice complete with invoiceId.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'

    put:
      summary: update invoice
      description: update path used to update point total for levelUp Member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '201':
          description: invoice successfully updated

    get:
      summary: Retrieves all the entries for invoice
      responses:
        '200':
          description: A list of invoice objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Invoice"


  /invoice/{invoiceId}:
    get:
      summary: get invoice
      parameters:
        - name: invoiceId
          in: path
          required: true
          schema:
            type: integer
      description: Get invoice information
      responses:
        '200':
          description: Returns invoice information for the requested invoice
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Invoice"

    delete:
      summary: delete product
      parameters:
        - name: invoiceId
          in: path
          required: true
          schema:
            type: integer
      description: deletes the invoice associated with the requested invoiceId
      responses:
        '204':
          description: Invoice successfully deleted.

  /invoiceItem:
    post:
      summary: add invoice item
      description: add a new invoiceitem by submmitting all fields except invoiceItemId.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceItem'
      responses:
        '201':
          description: Returns added invoice item complete with invoiceItemId.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceItem'


    put:
      summary: update invoice item
      description: update path used to update invoice item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceItem'
      responses:
        '201':
          description: product successfully updated

    get:
      summary: Retrieves all the entries for invoice items
      responses:
        '200':
          description: A list of invoice item objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InvoiceItem"

  /invoiceItemsByInvoiceId/{invoiceId}:
    get:
      summary: Retrieves all the entries for invoice items for a given invoice ID
      parameters:
        - name: invoiceId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of invoice item objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InvoiceItem"

  /invoiceItem/{invoiceItemId}:
    get:
      summary: get invoice item
      parameters:
        - name: invoiceItemId
          in: path
          required: true
          schema:
            type: integer
      description: Get invoice item information
      responses:
        '200':
          description: Returns invoice item information for the requested invoice item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvoiceItem"

    delete:
      summary: delete invoice item
      parameters:
        - name: invoiceItemId
          in: path
          required: true
          schema:
            type: integer
      description: deletes the invoice item associated with the requested invoiceItemId
      responses:
        '204':
          description: invoice item successfully deleted.

components:
  schemas:
    Invoice:
      properties:
        invoiceId:
          type: integer
        customerId:
          type: integer
        purchaseDate:
          type: string
      required:
        - customerId
        - purchaseDate

    InvoiceItem:
      properties:
        invoiceItemId:
          type: integer
        invoiceId:
          type: integer
        inventoryId:
          type: integer
        quantity:
          type: integer
        unitPrice:
          type: number
      required:
        - invoiceId
        - inventoryId
        - quantity
        - unitPrice